#ifndef MSGTYPE_H_
#define MSGTYPE_H_

#include <unordered_map>

namespace fix {

// ref: https://fiximate.fixtrading.org/legacy/en/FIX.5.0/tag35.html

enum FIXMsgType {
  Heartbeat,
  TestRequest,
  ResendRequest,
  Reject,
  SequenceReset,
  Logout,
  IOI,
  Advertisement,
  ExecutionReport,
  OrderCancelReject,
  Logon,
  News,
  Email,
  NewOrderSingle,
  NewOrderList,
  OrderCancelRequest,
  OrderCancelReplaceRequest,
  OrderStatusRequest,
  AllocationInstruction,
  ListCancelRequest,
  ListExecute,
  ListStatusRequest,
  ListStatus,
  AllocationInstructionAck,
  DontKnowTrade,
  QuoteRequest,
  Quote,
  SettlementInstructions,
  MarketDataRequest,
  MarketDataSnapshotFullRefresh,
  MarketDataIncrementalRefresh,
  MarketDataRequestReject,
  QuoteCancel,
  QuoteStatusRequest,
  MassQuoteAcknowledgement,
  SecurityDefinitionRequest,
  SecurityDefinition,
  SecurityStatusRequest,
  SecurityStatus,
  TradingSessionStatusRequest,
  TradingSessionStatus,
  MassQuote,
  BusinessMessageReject,
  BidRequest,
  BidResponse,
  ListStrikePrice,
  XMLNonFIX,
  RegistrationInstructions,
  RegistrationInstructionsResponse,
  OrderMassCancelRequest,
  OrderMassCancelReport,
  NewOrderCross,
  CrossOrderCancelReplaceRequest,
  CrossOrderCancelRequest,
  SecurityTypeRequest,
  SecurityTypes,
  SecurityListRequest,
  SecurityList,
  DerivativeSecurityListRequest,
  DerivativeSecurityList,
  NewOrderMultileg,
  MultilegOrderCancelReplace,
  TradeCaptureReportRequest,
  TradeCaptureReport,
  OrderMassStatusRequest,
  QuoteRequestReject,
  RFQRequest,
  QuoteStatusReport,
  QuoteResponse,
  Confirmation,
  PositionMaintenanceRequest,
  PositionMaintenanceReport,
  RequestForPositions,
  RequestForPositionsAck,
  PositionReport,
  TradeCaptureReportRequestAck,
  TradeCaptureReportAck,
  AllocationReport,
  AllocationReportAck,
  ConfirmationAck,
  SettlementInstructionRequest,
  AssignmentReport,
  CollateralRequest,
  CollateralAssignment,
  CollateralResponse,
  CollateralReport,
  CollateralInquiry,
  NetworkCounterpartySystemStatusRequest,
  NetworkCounterpartySystemStatusResponse,
  UserRequest,
  UserResponse,
  CollateralInquiryAck,
  ConfirmationRequest,
  TradingSessionListRequest,
  TradingSessionListRequest,
  TradingSessionList,
  SecurityListUpdateReport,
  AdjustedPositionReport,
  AllocationInstructionAlert,
  ExecutionAcknowledgement,
  ContraryIntentionReport,
  SecurityDefinitionUpdateReport,
};

static std::unordered_map<std::string, enum FIXMsgType> FIXMsgTypeMap{
    {"0", FIXMsgType::Heartbeat},
    {"1", FIXMsgType::TestRequest},
    {"2", FIXMsgType::ResendRequest},
    {"3", FIXMsgType::Reject},
    {"4", FIXMsgType::SequenceReset},
    {"5", FIXMsgType::Logout},
    {"6", FIXMsgType::IOI},
    {"7", FIXMsgType::Advertisement},
    {"8", FIXMsgType::ExecutionReport},
    {"9", FIXMsgType::OrderCancelReject},
    {"A", FIXMsgType::Logon},
    {"B", FIXMsgType::News},
    {"C", FIXMsgType::Email},
    {"D", FIXMsgType::NewOrderSingle},
    {"E", FIXMsgType::NewOrderList},
    {"F", FIXMsgType::OrderCancelRequest},
    {"G", FIXMsgType::OrderCancelReplaceRequest},
    {"H", FIXMsgType::OrderStatusRequest},
    {"J", FIXMsgType::AllocationInstruction},
    {"K", FIXMsgType::ListCancelRequest},
    {"L", FIXMsgType::ListExecute},
    {"M", FIXMsgType::ListStatusRequest},
    {"N", FIXMsgType::ListStatus},
    {"P", FIXMsgType::AllocationInstructionAck},
    {"Q", FIXMsgType::DontKnowTrade},
    {"R", FIXMsgType::QuoteRequest},
    {"S", FIXMsgType::Quote},
    {"T", FIXMsgType::SettlementInstructions},
    {"V", FIXMsgType::MarketDataRequest},
    {"W", FIXMsgType::MarketDataSnapshotFullRefresh},
    {"X", FIXMsgType::MarketDataIncrementalRefresh},
    {"Y", FIXMsgType::MarketDataRequestReject},
    {"Z", FIXMsgType::QuoteCancel},
    {"a", FIXMsgType::QuoteStatusRequest},
    {"b", FIXMsgType::MassQuoteAcknowledgement},
    {"c", FIXMsgType::SecurityDefinitionRequest},
    {"d", FIXMsgType::SecurityDefinition},
    {"e", FIXMsgType::SecurityStatusRequest},
    {"f", FIXMsgType::SecurityStatus},
    {"g", FIXMsgType::TradingSessionStatusRequest},
    {"h", FIXMsgType::TradingSessionStatus},
    {"i", FIXMsgType::MassQuote},
    {"j", FIXMsgType::BusinessMessageReject},
    {"k", FIXMsgType::BidRequest},
    {"l", FIXMsgType::BidResponse},
    {"m", FIXMsgType::ListStrikePrice},
    {"n", FIXMsgType::XMLNonFIX},
    {"o", FIXMsgType::RegistrationInstructions},
    {"p", FIXMsgType::RegistrationInstructionsResponse},
    {"q", FIXMsgType::OrderMassCancelRequest},
    {"r", FIXMsgType::OrderMassCancelReport},
    {"s", FIXMsgType::NewOrderCross},
    {"t", FIXMsgType::CrossOrderCancelReplaceRequest},
    {"u", FIXMsgType::CrossOrderCancelRequest},
    {"v", FIXMsgType::SecurityTypeRequest},
    {"w", FIXMsgType::SecurityTypes},
    {"x", FIXMsgType::SecurityListRequest},
    {"y", FIXMsgType::SecurityList},
    {"z", FIXMsgType::DerivativeSecurityListRequest},
    {"AA", FIXMsgType::DerivativeSecurityList},
    {"AB", FIXMsgType::NewOrderMultileg},
    {"AC", FIXMsgType::MultilegOrderCancelReplace},
    {"AD", FIXMsgType::TradeCaptureReportRequest},
    {"AE", FIXMsgType::TradeCaptureReport},
    {"AF", FIXMsgType::OrderMassStatusRequest},
    {"AG", FIXMsgType::QuoteRequestReject},
    {"AH", FIXMsgType::RFQRequest},
    {"AI", FIXMsgType::QuoteStatusReport},
    {"AJ", FIXMsgType::QuoteResponse},
    {"AK", FIXMsgType::Confirmation},
    {"AL", FIXMsgType::PositionMaintenanceRequest},
    {"AM", FIXMsgType::PositionMaintenanceReport},
    {"AN", FIXMsgType::RequestForPositions},
    {"AO", FIXMsgType::RequestForPositionsAck},
    {"AP", FIXMsgType::PositionReport},
    {"AQ", FIXMsgType::TradeCaptureReportRequestAck},
    {"AR", FIXMsgType::TradeCaptureReportAck},
    {"AS", FIXMsgType::AllocationReport},
    {"AT", FIXMsgType::AllocationReportAck},
    {"AU", FIXMsgType::ConfirmationAck},
    {"AV", FIXMsgType::SettlementInstructionRequest},
    {"AW", FIXMsgType::AssignmentReport},
    {"AX", FIXMsgType::CollateralRequest},
    {"AY", FIXMsgType::CollateralAssignment},
    {"AZ", FIXMsgType::CollateralResponse},
    {"BA", FIXMsgType::CollateralReport},
    {"BB", FIXMsgType::CollateralInquiry},
    {"BC", FIXMsgType::NetworkCounterpartySystemStatusRequest},
    {"BD", FIXMsgType::NetworkCounterpartySystemStatusResponse},
    {"BE", FIXMsgType::UserRequest},
    {"BF", FIXMsgType::UserResponse},
    {"BG", FIXMsgType::CollateralInquiryAck},
    {"BH", FIXMsgType::ConfirmationRequest},
    {"BI", FIXMsgType::TradingSessionListRequest},
    {"BJ", FIXMsgType::TradingSessionList},
    {"BK", FIXMsgType::SecurityListUpdateReport},
    {"BL", FIXMsgType::AdjustedPositionReport},
    {"BM", FIXMsgType::AllocationInstructionAlert},
    {"BN", FIXMsgType::ExecutionAcknowledgement},
    {"BO", FIXMsgType::ConfirmationRequest},
    {"BP", FIXMsgType::SecurityDefinitionUpdateReport}};

}  // namespace fix

#endif